In [4]:
import pandas as pd

df = pd.read_csv('qgea-i56i.csv')
print(df.head())

  cmplnt_num             cmplnt_fr_dt cmplnt_fr_tm             cmplnt_to_dt  \
0  318216640  2025-12-31T00:00:00.000     22:00:00  2025-12-31T00:00:00.000
1  318184134  2025-12-30T00:00:00.000     23:00:00  2025-12-31T00:00:00.000
2  318206310  2025-12-31T00:00:00.000     21:00:00  2025-12-31T00:00:00.000
3  318192938  2025-12-31T00:00:00.000     06:40:00  2025-12-31T00:00:00.000
4  318191345  2025-12-31T00:00:00.000     09:35:00  2025-12-31T00:00:00.000

  cmplnt_to_tm  addr_pct_cd                   rpt_dt  ky_cd  \
0     22:12:00           49  2025-12-31T00:00:00.000    341
1     06:00:00           45  2025-12-31T00:00:00.000    110
2     21:09:00           67  2025-12-31T00:00:00.000    359
3     06:40:00           42  2025-12-31T00:00:00.000    578
4     09:40:00           25  2025-12-31T00:00:00.000    126

                        ofns_desc  pd_cd  ... susp_sex transit_district  \
0                   PETIT LARCENY  339.0  ...        U              NaN
1  GRAND LARCENY OF MOTOR VEHICLE  441.0  ...   (null)              NaN
2  OFFENSES AGAINST PUBLIC ADMINI  750.0  ...        M              NaN
3                   HARRASSMENT 2  638.0  ...        M              NaN
4         MISCELLANEOUS PENAL LAW  198.0  ...   (null)              NaN

    latitude  longitude                      lat_lon              patrol_boro  \
0  40.858746 -73.865615      (40.858746, -73.865615)        PATROL BORO BRONX
1  40.818751 -73.814761      (40.818751, -73.814761)        PATROL BORO BRONX
2  40.660770 -73.919742  (40.66077022, -73.91974234)  PATROL BORO BKLYN SOUTH
3  40.824267 -73.909296      (40.824267, -73.909296)        PATROL BORO BRONX
4  40.799530 -73.932839       (40.79953, -73.932839)    PATROL BORO MAN NORTH

  station_name  vic_age_group        vic_race vic_sex
0       (null)          25-44  BLACK HISPANIC       M
1       (null)          25-44           WHITE       M
2       (null)        UNKNOWN         UNKNOWN       E
3       (null)          18-24  WHITE HISPANIC       F
4       (null)          45-64  BLACK HISPANIC       F

[5 rows x 35 columns]

In [5]:
df.shape

(100000, 35)

In [6]:
df.head()

,cmplnt_num,cmplnt_fr_dt,cmplnt_fr_tm,cmplnt_to_dt,cmplnt_to_tm,addr_pct_cd,rpt_dt,ky_cd,ofns_desc,pd_cd,...,susp_sex,transit_district,latitude,longitude,lat_lon,patrol_boro,station_name,vic_age_group,vic_race,vic_sex
0,318216640,2025-12-31T00:00:00.000,22:00:00,2025-12-31T00:00:00.000,22:12:00,49,2025-12-31T00:00:00.000,341,PETIT LARCENY,339.0,...,U,NaN,40.858746,-73.865615,"(40.858746, -73.865615)",PATROL BORO BRONX,(null),25-44,BLACK HISPANIC,M
1,318184134,2025-12-30T00:00:00.000,23:00:00,2025-12-31T00:00:00.000,06:00:00,45,2025-12-31T00:00:00.000,110,GRAND LARCENY OF MOTOR VEHICLE,441.0,...,(null),NaN,40.818751,-73.814761,"(40.818751, -73.814761)",PATROL BORO BRONX,(null),25-44,WHITE,M
2,318206310,2025-12-31T00:00:00.000,21:00:00,2025-12-31T00:00:00.000,21:09:00,67,2025-12-31T00:00:00.000,359,OFFENSES AGAINST PUBLIC ADMINI,750.0,...,M,NaN,40.660770,-73.919742,"(40.66077022, -73.91974234)",PATROL BORO BKLYN SOUTH,(null),UNKNOWN,UNKNOWN,E
3,318192938,2025-12-31T00:00:00.000,06:40:00,2025-12-31T00:00:00.000,06:40:00,42,2025-12-31T00:00:00.000,578,HARRASSMENT 2,638.0,...,M,NaN,40.824267,-73.909296,"(40.824267, -73.909296)",PATROL BORO BRONX,(null),18-24,WHITE HISPANIC,F
4,318191345,2025-12-31T00:00:00.000,09:35:00,2025-12-31T00:00:00.000,09:40:00,25,2025-12-31T00:00:00.000,126,MISCELLANEOUS PENAL LAW,198.0,...,(null),NaN,40.799530,-73.932839,"(40.79953, -73.932839)",PATROL BORO MAN NORTH,(null),45-64,BLACK HISPANIC,F

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 35 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   cmplnt_num         100000 non-null  object
 1   cmplnt_fr_dt       100000 non-null  object
 2   cmplnt_fr_tm       100000 non-null  object
 3   cmplnt_to_dt       95763 non-null   object
 4   cmplnt_to_tm       100000 non-null  object
 5   addr_pct_cd        100000 non-null  int64
 6   rpt_dt             100000 non-null  object
 7   ky_cd              100000 non-null  int64
 8   ofns_desc          100000 non-null  object
 9   pd_cd              99963 non-null   float64
 10  pd_desc            100000 non-null  object
 11  crm_atpt_cptd_cd   100000 non-null  object
 12  law_cat_cd         100000 non-null  object
 13  boro_nm            100000 non-null  object
 14  loc_of_occur_desc  100000 non-null  object
 15  prem_typ_desc      100000 non-null  object
 16  juris_desc         100000 non-null  object
 17  jurisdiction_code  100000 non-null  int64
 18  parks_nm           100000 non-null  object
 19  hadevelopt         100000 non-null  object
 20  housing_psa        100000 non-null  object
 21  x_coord_cd         100000 non-null  int64
 22  y_coord_cd         100000 non-null  int64
 23  susp_age_group     100000 non-null  object
 24  susp_race          100000 non-null  object
 25  susp_sex           100000 non-null  object
 26  transit_district   5553 non-null    float64
 27  latitude           100000 non-null  float64
 28  longitude          100000 non-null  float64
 29  lat_lon            100000 non-null  object
 30  patrol_boro        100000 non-null  object
 31  station_name       100000 non-null  object
 32  vic_age_group      100000 non-null  object
 33  vic_race           100000 non-null  object
 34  vic_sex            100000 non-null  object
dtypes: float64(4), int64(5), object(26)
memory usage: 26.7+ MB

In [8]:
df.columns.tolist()

['cmplnt_num',
 'cmplnt_fr_dt',
 'cmplnt_fr_tm',
 'cmplnt_to_dt',
 'cmplnt_to_tm',
 'addr_pct_cd',
 'rpt_dt',
 'ky_cd',
 'ofns_desc',
 'pd_cd',
 'pd_desc',
 'crm_atpt_cptd_cd',
 'law_cat_cd',
 'boro_nm',
 'loc_of_occur_desc',
 'prem_typ_desc',
 'juris_desc',
 'jurisdiction_code',
 'parks_nm',
 'hadevelopt',
 'housing_psa',
 'x_coord_cd',
 'y_coord_cd',
 'susp_age_group',
 'susp_race',
 'susp_sex',
 'transit_district',
 'latitude',
 'longitude',
 'lat_lon',
 'patrol_boro',
 'station_name',
 'vic_age_group',
 'vic_race',
 'vic_sex']

In [10]:
columns_to_keep = [
    'cmplnt_num',
    'cmplnt_fr_dt',
    'cmplnt_fr_tm',
    'ofns_desc',
    'law_cat_cd',
    'boro_nm',
    'prem_typ_desc',
    'latitude',
    'longitude',
    'susp_age_group',
    'susp_race',
    'susp_sex',
    'vic_age_group',
    'vic_race',
    'vic_sex'
]

df = df[columns_to_keep]

In [11]:
df.isnull().sum().sort_values(ascending=False)

cmplnt_num        0
cmplnt_fr_dt      0
cmplnt_fr_tm      0
ofns_desc         0
law_cat_cd        0
boro_nm           0
prem_typ_desc     0
latitude          0
longitude         0
susp_age_group    0
susp_race         0
susp_sex          0
vic_age_group     0
vic_race          0
vic_sex           0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [16]:
df['cmplnt_fr_dt'] = pd.to_datetime(
    df['cmplnt_fr_dt'],
    errors='coerce'
)

In [17]:
df['cmplnt_fr_dt'].dtype

dtype('<M8[ns]')

In [19]:
df['year'] = df['cmplnt_fr_dt'].dt.year
df['month'] = df['cmplnt_fr_dt'].dt.month_name()
df['day_of_week'] = df['cmplnt_fr_dt'].dt.day_name()

df['hour'] = pd.to_datetime(
    df['cmplnt_fr_tm'],
    format='%H:%M:%S',
    errors='coerce'
).dt.hour

In [20]:
df[['year','month','day_of_week','hour']].head()

     year     month day_of_week  hour
0  2025.0  December   Wednesday    22
1  2025.0  December     Tuesday    23
2  2025.0  December   Wednesday    21
3  2025.0  December   Wednesday     6
4  2025.0  December   Wednesday     9

In [32]:
df.to_csv('nyc_crime_cleaned.csv', index=False)